language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- python -m pytest -v
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: YcJAx7nC7DFtkWEdtUNQss+rsg6hgdhqfSJYFBvfFRoxoeNOv/HmIk9oY2MkTIhw9qexLe+cltk5RmUdtJQfNoxOE/LrILEMf3Poyefc8b9nhVCpaMN4fgYGgf4XpTFXacqzOGbCXAx3edEbmMtENmI2c0zgX/VWs+WC3AhF3VDoQaTTpsFIlmuTpniFPBhikVZcVSxND5RASijOTSsevgFs95KLaqXL1+YsaZYvfXVUUDa1BjyaWsnIoAlWv/MH/g1bHt3wcMU/G+gRMOsiyso49LiZSoW9HOXQ6NbXDPc1wYclBn0AfaL8XT1iwP0/Z0Fxlqliby1amq43O+13riwVCi5JRJ21uF3YlsVA+QcC3KZTpjxka0V6B38zfSYx4FYOUlhCWlyWJUIjA/Ro+kJmQ9Fz7ENYXMPhIeMyARdep4UsWWShwnSzzXaPt77tuGsyILoggkfF4GJ6ks2Pg9MFM/kV39wUonlTISerlNuKJVkOOMkYKoy8Ul1S36FY2+q8nYsju7Q9qxMZPQCL2T5MslkAGfmO6REOgJu4C1OHHn1T+LvUwtn+e+MLbwQW1Z4WjyO26nvnUBLWslGjWmt1pamSGyZslvwL0rnyuwL/DKw2aiEoV4tDeOWe+KX1geUoH93LC1ExSho7/dL8gv/iwtuFhFd/OlNulEf745s=
  on:
    tags: true
    all_branches: true
    python: 3.6
