language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- python -m pytest -v
deploy:
  provider: pypi
  user: ip
  password:
    secure: j7KDuXfP0CLc/9VD7xlBV99Y8wyfkRD6Yjf/4crDifsRK4telR/BTj2Jr+smPoYhqlsy5IlojagCyG72bzARCMfhE1eA/DUxdLJ2a5S/edeUxbnBwx1R7Fv7SKlD8EVrPeY0l1g72EvNVfeXMjo0WJfhH1qYsaY022jUImSF6Xy7kw1bi4i3VDNdMPHaWRNdq3WpVX4JR4lgMvvHOWU14yfHqg2UAxG2RrrRwd33MajZqGcyRphlR5umUa9nHChDwIAt5CL8uxhVe3Ktr8lhM9utyoYcl+Y7MMhDJH6x45LI2vxuTMpWBNE0IIuYmoweQfbnBB7IpaW/2GiJ+PP6oUhEaqazVtadCQ/neRdO5ACJqO6sRn2Fxj6yvGVoEI4bCybWO8q3ROJNzkTMe4I72W8N0dzl9L7pfVDBec6BG+uf3q6t+E4JOV5jgIAN2Bt7c2Zg8td4epLni5xJSwqcQcV989Y3Dc6BCcDmeu+spnyG+hUXx/EY5pmYvMrKX/ZKmX4gXVq1vz/VyuRoiDYQ0oJOqee0d+zV0TLPEgjyZVilIBEIZhmjzWjuDTOeHIJjL7XRW6elTMnd3ZuqTZcdUHiYNrwJ3eRmQeKwo4N3a/YNesSuW5g7m0WyI/+PcHXXrqULlcyyoWjRmu3ClELDFcAlCiRuO4Yx+GRceHeSfGs=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    all_branches: true
    python: 3.7
